services:
#Service  
    #tmt uploader service
    uploader_service:
        class: Tmt\ServicesBundle\Services\Uploader\Uploader
    #tmt pagination service    
    pagination_service:
        class: Tmt\ServicesBundle\Services\Pagination\Pagination
        arguments: ["@router","@request_stack"]
    #tmt office service    
    office_service:
        class: Tmt\ServicesBundle\Services\Office\Excel
        arguments: ["@phpexcel","%kernel.root_dir%"] 
    #tmt async service
    async_service:
        class: 'Tmt\ServicesBundle\Services\AsyncService\AsyncService'
        arguments: ["%kernel.root_dir%"]
        
#Twig extension 
    #tmt time ago extension
    time.ago.extension:
        class: Tmt\ServicesBundle\Twig\TimeAgoEx\TimeAgoExtension
        tags:
            - { name: twig.extension }         
    #tmt Tmt extension
    tmt.extension:
        class: Tmt\ServicesBundle\Twig\TmtExtension\TmtExtension
        arguments: ["@router"]
        tags:
            - { name: twig.extension }  
    
    video.extension:
        class: Tmt\ServicesBundle\Twig\VideoEx\VideoExtension
        tags:
            - { name: twig.extension } 
                